export const encouragements = [
  'Three tasks complete — your day is moving in the right direction.',
  'Great pace: three tasks are already behind you.',
  'That is the first three. Keep going at your own pace.',
  'Lovely progress — your list is noticeably shorter.',
  'Three tasks complete. Small steps add up beautifully.',
  'You already have something to be proud of today.',
  'You have found a wonderful working rhythm.',
  'Three items checked off. Your focus is working.',
  'A strong start — three wins already today.',
  'Keep it up: three more tasks are off your mind.',
  'The day feels lighter with three tasks complete.',
  'Your progress is shining through.',
  'Three tasks are a lovely reason to celebrate.',
  'Things are moving — three items can be crossed off.',
  'You are not just planning — you are finishing.',
  'A smooth move: three tasks complete without the fuss.',
  'The first three are done. Keep moving gently.',
  'Today’s list already looks much sweeter.',
  'Three finished tasks make a meaningful milestone.',
  'Progress unlocked: three tasks complete.',
  'You have already moved your day forward.',
  'Three completions in a row — a lovely burst of momentum.',
  'A little more calm for your mind and your list.',
  'You already have three small wins today.',
  'Progress saved: three tasks checked off.',
  'The list gets smaller while your progress grows.',
  'Three tasks done — a perfect moment to enjoy your pace.',
  'A lovely streak: three tasks are now complete.',
  'You moved your day forward by three bright steps.',
  'Three tasks behind you. Keep the rhythm that feels good.'
];
