import type { FocusToolState } from '../types';
const key = 'focus-tool:v1';
const currencies=['USD','EUR','GBP','RUB'];
export const defaults = (): FocusToolState => ({ schemaVersion:2, profile:{name:''}, checkIns:{}, tasks:[], focusSessions:[], pointEvents:[], milestones:{}, activeTimer:{mode:'focus',status:'idle',plannedSeconds:1500,remainingSeconds:1500}, focusSettings:{focusMinutes:25,shortBreakMinutes:5,longBreakMinutes:20,sessionsBeforeLongBreak:4,dailyFocusGoalMinutes:90,soundEnabled:false}, completedFocusCountSinceLongBreak:0, groups:[], incomeCurrency:'RUB', attendance:{}, periodTracking:{days:{},markers:[],settings:{predictionEnabled:false,averageCycleDays:28,averagePeriodDays:5,periodReminderDaysBefore:1,periodReminderTime:'09:00'}}, notifications:{enabled:false,privateMode:true,delivered:[],dismissed:[]}, privacy:{autoLockMinutes:5} });

export const normalizeState = (value:unknown):FocusToolState => {
  const x=value&&typeof value==='object'?value as any:{};
  const fallback=defaults();
  const incomeCurrency=currencies.includes(x.incomeCurrency)?x.incomeCurrency:'RUB';
  const groups=Array.isArray(x.groups)?x.groups.map((group:any)=>({...group,scheduleWeekdays:Array.isArray(group.scheduleWeekdays)?group.scheduleWeekdays:[],children:Array.isArray(group.children)?group.children.map((child:any)=>({...child,payments:Array.isArray(child.payments)?child.payments.map((payment:any)=>({...payment,currency:currencies.includes(payment.currency)?payment.currency:incomeCurrency})):[]})):[]})):[];
  const markers=Array.isArray(x.periodTracking?.markers)?x.periodTracking.markers.map((marker:any)=>({...marker,kind:marker.kind==='ring'||/ring|кольц/i.test(String(marker.title||''))?'ring':'custom',time:/^\d{2}:\d{2}$/.test(marker.time||'')?marker.time:'09:00',reminderMinutesBefore:Array.isArray(marker.reminderMinutesBefore)?marker.reminderMinutesBefore.filter((item:any)=>Number.isFinite(item)&&item>=0):[Math.max(0,Number(marker.remindDaysBefore)||0)*1440]})):[];
  return {...fallback,...x,schemaVersion:2,profile:{...fallback.profile,...x.profile},tasks:Array.isArray(x.tasks)?x.tasks:[],focusSessions:Array.isArray(x.focusSessions)?x.focusSessions:[],pointEvents:Array.isArray(x.pointEvents)?x.pointEvents:[],checkIns:x.checkIns&&typeof x.checkIns==='object'?x.checkIns:{},milestones:x.milestones&&typeof x.milestones==='object'?x.milestones:{},activeTimer:{...fallback.activeTimer,...x.activeTimer},focusSettings:{...fallback.focusSettings,...x.focusSettings},groups,incomeCurrency,attendance:x.attendance&&typeof x.attendance==='object'?x.attendance:{},periodTracking:{...fallback.periodTracking,...x.periodTracking,days:x.periodTracking?.days&&typeof x.periodTracking.days==='object'?x.periodTracking.days:{},markers,settings:{...fallback.periodTracking.settings,...x.periodTracking?.settings}},notifications:{...fallback.notifications,...x.notifications,delivered:Array.isArray(x.notifications?.delivered)?x.notifications.delivered.slice(-300):[],dismissed:Array.isArray(x.notifications?.dismissed)?x.notifications.dismissed.slice(-300):[]},privacy:{...fallback.privacy,...x.privacy}};
};

export const load = (): FocusToolState => { try { const raw=localStorage.getItem(key); return raw?normalizeState(JSON.parse(raw)):defaults(); } catch(e) { console.warn('Focus Tool storage could not be read',e); return defaults(); } };
export const save = (state: FocusToolState) => { try { localStorage.setItem(key, JSON.stringify({...state,schemaVersion:2,notifications:{...state.notifications,delivered:state.notifications.delivered.slice(-300),dismissed:state.notifications.dismissed.slice(-300)}})); return true; } catch(e) { console.warn('Focus Tool storage could not be saved',e); return false; } };
export const makeBackup = (state:FocusToolState) => JSON.stringify({kind:'focus-tool-backup',version:2,exportedAt:new Date().toISOString(),state:{...state,schemaVersion:2}},null,2);
export const readBackup = (text:string) => { const parsed=JSON.parse(text); if(parsed?.kind!=='focus-tool-backup'||!parsed.state)throw new Error('This is not a Focus Tool backup.'); return normalizeState(parsed.state); };
export const resetStorage = () => { try { localStorage.removeItem(key); } catch(e) { console.warn('Focus Tool storage could not be reset',e); } };
