import { Cloud,CloudOff,Download,HardDrive,Import,Lock,LogIn,LogOut,RefreshCw,Save,ScanFace,ShieldCheck,Trash2,X } from 'lucide-react';
import { useEffect,useRef,useState } from 'react';
import { makeBackup,readBackup } from '../repositories/localProgressRepository';
import { hashPin,pinIsValid } from '../lib/security';
import { authenticateWithBiometrics,biometricUnlockAvailable,clearBiometricUnlock,enableBiometricUnlock,hasBiometricUnlock } from '../lib/biometricLock';
import type { FocusToolState,NotificationSettings,PrivacySettings } from '../types';
import type { CloudSyncController } from '../lib/cloudSync';

export function DataPrivacyModal({state,cloud,onClose,onRestore,onPrivacy,onNotifications,onLock}:{state:FocusToolState;cloud:CloudSyncController;onClose:()=>void;onRestore:(state:FocusToolState)=>void;onPrivacy:(privacy:PrivacySettings)=>void;onNotifications:(settings:NotificationSettings)=>void;onLock:()=>void}){
  const inputRef=useRef<HTMLInputElement>(null);const [pin,setPin]=useState(''),[message,setMessage]=useState(''),[biometricAvailable,setBiometricAvailable]=useState(false),[biometricEnabled,setBiometricEnabled]=useState(hasBiometricUnlock),[biometricBusy,setBiometricBusy]=useState(false);
  useEffect(()=>{const close=(event:KeyboardEvent)=>{if(event.key==='Escape')onClose()};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close)},[onClose]);
  useEffect(()=>{let active=true;void biometricUnlockAvailable().then(available=>{if(active)setBiometricAvailable(available)});return()=>{active=false}},[]);
  const exportData=async()=>{const name=`focus-tool-backup-${new Date().toISOString().slice(0,10)}.json`,file=new File([makeBackup(state)],name,{type:'application/json'}),shareNavigator=navigator as Navigator&{canShare?:(data:ShareData)=>boolean};try{if(navigator.share&&shareNavigator.canShare?.({files:[file]}))await navigator.share({title:'Focus Tool backup',files:[file]});else{const url=URL.createObjectURL(file),anchor=document.createElement('a');anchor.href=url;anchor.download=name;anchor.click();window.setTimeout(()=>URL.revokeObjectURL(url),1000)}onPrivacy({...state.privacy,lastBackupAt:Date.now()});setMessage('Backup created. Keep it somewhere safe.')}catch(error){if((error as DOMException)?.name!=='AbortError')setMessage('The backup could not be exported.')}};
  const importData=async(file?:File)=>{if(!file)return;try{const restored=readBackup(await file.text());if(window.confirm('Replace the data on this device with this backup?')){onRestore(restored);setMessage('Backup restored successfully.')}}catch(error){setMessage(error instanceof Error?error.message:'The backup could not be opened.')}finally{if(inputRef.current)inputRef.current.value=''}};
  const savePin=async()=>{if(!pinIsValid(pin)){setMessage('Use 4–8 digits for the app code.');return}if(!state.privacy.pinHash){clearBiometricUnlock();setBiometricEnabled(false)}onPrivacy({...state.privacy,pinHash:await hashPin(pin)});setPin('');setMessage('App lock enabled.')};
  const removePin=()=>{if(window.confirm('Turn off the app lock on this device?')){clearBiometricUnlock();setBiometricEnabled(false);onPrivacy({...state.privacy,pinHash:undefined});setMessage('App lock removed.')}};
  const enableFaceId=async()=>{setBiometricBusy(true);setMessage('');try{await enableBiometricUnlock();setBiometricEnabled(true);setMessage('Face ID unlock is ready on this device.')}catch(error){setMessage(error instanceof DOMException&&error.name==='NotAllowedError'?'Face ID setup was cancelled.':error instanceof Error?error.message:'Face ID could not be enabled.')}finally{setBiometricBusy(false)}};
  const disableFaceId=()=>{if(window.confirm('Remove Face ID unlock from this device?')){clearBiometricUnlock();setBiometricEnabled(false);setMessage('Face ID unlock removed.')}};
  const syncText=cloud.status==='saved'?'All changes are saved':cloud.status==='syncing'||cloud.status==='connecting'?'Syncing your changes…':cloud.status==='offline'?'Offline · changes stay safely on this device':cloud.status==='error'?'Cloud sync needs attention':'Local storage only';
  return <div className="modal-backdrop" onMouseDown={onClose}><section className="modal privacy-modal" role="dialog" aria-modal="true" aria-label="Data and privacy" onMouseDown={event=>event.stopPropagation()}><div className="modal-head"><div><small>DATA, ACCOUNT & PRIVACY</small><h2>Your information</h2></div><button className="icon" onClick={onClose} aria-label="Close"><X size={18}/></button></div>
    <div className="storage-status">{cloud.account?<Cloud size={23}/>:<HardDrive size={23}/>}<span><strong>{cloud.account?'Google cloud sync':'Saved on this device'}</strong><small>{cloud.account?syncText:state.privacy.lastBackupAt?`Last backup ${new Date(state.privacy.lastBackupAt).toLocaleDateString('en-US')}`:'Connect Google to sync across devices'}</small></span>{cloud.account&&cloud.status!=='offline'&&cloud.status!=='error'?<Save size={18}/>:cloud.account?<CloudOff size={18}/>:<Save size={18}/>}</div>
    <section className="privacy-section cloud-account"><div className="privacy-section-title"><Cloud size={19}/><div><strong>Google account</strong><small>{cloud.account?'Your local data is connected to this account.':'Sign in once to back up and sync every section of the app.'}</small></div></div>{cloud.account?<><div className="cloud-profile">{cloud.account.photoURL?<img src={cloud.account.photoURL} alt="" referrerPolicy="no-referrer"/>:<span>{cloud.account.displayName.slice(0,1).toUpperCase()}</span>}<div><strong>{cloud.account.displayName}</strong><small>{cloud.account.email}</small></div></div><div className="privacy-actions"><button className="secondary" onClick={()=>cloud.queueSave(state)} disabled={cloud.status==='syncing'}><RefreshCw size={16}/> Sync now</button><button className="secondary" onClick={()=>void cloud.signOut()}><LogOut size={16}/> Sign out</button></div></>:<button className="primary google-sign-in" onClick={()=>void cloud.signIn()} disabled={cloud.status==='connecting'}><LogIn size={17}/> {cloud.status==='connecting'?'Connecting…':'Continue with Google'}</button>}{cloud.error&&<p className="cloud-error" role="alert">{cloud.error}</p>}</section>
    <section className="privacy-section"><div className="privacy-section-title"><Download size={19}/><div><strong>Backup</strong><small>Protect groups, payments, expenses, attendance, tasks, and personal notes.</small></div></div><div className="privacy-actions"><button className="primary" onClick={exportData}><Download size={16}/> Export backup</button><button className="secondary" onClick={()=>inputRef.current?.click()}><Import size={16}/> Import backup</button><input ref={inputRef} className="visually-hidden" type="file" accept="application/json,.json" onChange={event=>importData(event.target.files?.[0])}/></div></section>
    <section className="privacy-section"><div className="privacy-section-title"><ShieldCheck size={19}/><div><strong>Private notifications</strong><small>Hide task, period, and ring details on the lock screen.</small></div></div><label className="period-toggle"><input type="checkbox" checked={state.notifications.privateMode} onChange={event=>onNotifications({...state.notifications,privateMode:event.target.checked})}/><span>Use neutral notification text</span></label></section>
    <section className="privacy-section"><div className="privacy-section-title"><Lock size={19}/><div><strong>App lock</strong><small>{state.privacy.pinHash?'Use Face ID or your code when the app locks.':'Add a 4–8 digit code for this device.'}</small></div></div><div className="pin-row"><input aria-label="New app code" type="password" inputMode="numeric" pattern="[0-9]*" maxLength={8} value={pin} onChange={event=>setPin(event.target.value.replace(/\D/g,''))} placeholder={state.privacy.pinHash?'New code':'4–8 digits'}/><button className="secondary" onClick={savePin}>{state.privacy.pinHash?'Change':'Enable'}</button></div><p className="form-hint">The code locks the app screen. Data and exported backups remain stored locally and are not encrypted.</p>{state.privacy.pinHash&&<><div className={`biometric-setting ${biometricEnabled?'enabled':''}`}><ScanFace size={23}/><span><strong>Face ID</strong><small>{biometricEnabled?'Enabled on this device':biometricAvailable?'Use Face ID for faster unlock':'Not available in this browser'}</small></span>{biometricEnabled?<button className="secondary compact" onClick={disableFaceId}>Remove</button>:<button className="primary compact" disabled={!biometricAvailable||biometricBusy} onClick={()=>void enableFaceId()}>{biometricBusy?'Setting up…':'Enable'}</button>}</div><label>Auto-lock<select value={state.privacy.autoLockMinutes} onChange={event=>onPrivacy({...state.privacy,autoLockMinutes:Number(event.target.value)})}><option value="0">Whenever I leave the app</option><option value="1">After 1 minute</option><option value="5">After 5 minutes</option><option value="15">After 15 minutes</option><option value="60">After 1 hour</option></select></label><div className="privacy-actions"><button className="secondary" onClick={onLock}><Lock size={16}/> Lock now</button><button className="danger" onClick={removePin}><Trash2 size={16}/> Remove code</button></div></>}</section>
    {message&&<p className="privacy-message" role="status">{message}</p>}
  </section></div>;
}

export function LockScreen({pinHash,onUnlock}:{pinHash:string;onUnlock:()=>void}){
  const biometricEnabled=hasBiometricUnlock();
  const attemptedBiometric=useRef(false);
  const [pin,setPin]=useState(''),[error,setError]=useState(''),[biometricBusy,setBiometricBusy]=useState(biometricEnabled),[biometricFinished,setBiometricFinished]=useState(!biometricEnabled);
  const unlock=async(event:React.FormEvent)=>{event.preventDefault();if(await hashPin(pin)===pinHash){setError('');onUnlock()}else{setError('That code is not correct.');setPin('')}};
  const unlockWithFaceId=async(automatic=false)=>{if(!automatic&&biometricBusy)return;setBiometricBusy(true);setBiometricFinished(false);setError('');try{if(await authenticateWithBiometrics())onUnlock();else setError('Face ID is not available. Use your app code.')}catch(reason){setError(reason instanceof DOMException&&reason.name==='NotAllowedError'?'Face ID was not completed. Use your code or try again.':'Face ID could not unlock the app. Use your code.')}finally{setBiometricBusy(false);setBiometricFinished(true)}};
  useEffect(()=>{if(biometricEnabled&&!attemptedBiometric.current){attemptedBiometric.current=true;void unlockWithFaceId(true)}},[biometricEnabled]);
  return <main className="lock-screen"><form onSubmit={unlock}><img src={`${import.meta.env.BASE_URL}icons/focus-tool-192.png`} alt=""/><small>FOCUS TOOL</small><h1>Welcome back</h1><p>{biometricEnabled&&!biometricFinished?'Starting Face ID…':biometricEnabled?'Enter your code if Face ID was not completed.':'Enter your app code to continue.'}</p>{biometricEnabled&&biometricFinished&&<><button type="button" className="primary face-id-unlock" disabled={biometricBusy} onClick={()=>void unlockWithFaceId()}><ScanFace size={20}/> Try Face ID again</button><span className="lock-divider">or use your code</span></>}<input autoFocus={!biometricEnabled} aria-label="App code" type="password" inputMode="numeric" pattern="[0-9]*" maxLength={8} value={pin} onChange={event=>setPin(event.target.value.replace(/\D/g,''))} placeholder="••••"/><button className={biometricEnabled?'secondary':'primary'} disabled={!pinIsValid(pin)}><Lock size={17}/> Unlock with code</button>{error&&<span role="alert">{error}</span>}</form></main>;
}
