import { Download,HardDrive,Import,Lock,Save,ShieldCheck,Trash2,X } from 'lucide-react';
import { useEffect,useRef,useState } from 'react';
import { makeBackup,readBackup } from '../repositories/localProgressRepository';
import { hashPin,pinIsValid } from '../lib/security';
import type { FocusToolState,NotificationSettings,PrivacySettings } from '../types';

export function DataPrivacyModal({state,onClose,onRestore,onPrivacy,onNotifications,onLock}:{state:FocusToolState;onClose:()=>void;onRestore:(state:FocusToolState)=>void;onPrivacy:(privacy:PrivacySettings)=>void;onNotifications:(settings:NotificationSettings)=>void;onLock:()=>void}){
  const inputRef=useRef<HTMLInputElement>(null);const [pin,setPin]=useState(''),[message,setMessage]=useState('');
  useEffect(()=>{const close=(event:KeyboardEvent)=>{if(event.key==='Escape')onClose()};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close)},[onClose]);
  const exportData=async()=>{const name=`focus-tool-backup-${new Date().toISOString().slice(0,10)}.json`,file=new File([makeBackup(state)],name,{type:'application/json'}),shareNavigator=navigator as Navigator&{canShare?:(data:ShareData)=>boolean};try{if(navigator.share&&shareNavigator.canShare?.({files:[file]}))await navigator.share({title:'Focus Tool backup',files:[file]});else{const url=URL.createObjectURL(file),anchor=document.createElement('a');anchor.href=url;anchor.download=name;anchor.click();window.setTimeout(()=>URL.revokeObjectURL(url),1000)}onPrivacy({...state.privacy,lastBackupAt:Date.now()});setMessage('Backup created. Keep it somewhere safe.')}catch(error){if((error as DOMException)?.name!=='AbortError')setMessage('The backup could not be exported.')}};
  const importData=async(file?:File)=>{if(!file)return;try{const restored=readBackup(await file.text());if(window.confirm('Replace the data on this device with this backup?')){onRestore(restored);setMessage('Backup restored successfully.')}}catch(error){setMessage(error instanceof Error?error.message:'The backup could not be opened.')}finally{if(inputRef.current)inputRef.current.value=''}};
  const savePin=async()=>{if(!pinIsValid(pin)){setMessage('Use 4–8 digits for the app code.');return}onPrivacy({...state.privacy,pinHash:await hashPin(pin)});setPin('');setMessage('App lock enabled.')};
  const removePin=()=>{if(window.confirm('Turn off the app lock on this device?')){onPrivacy({...state.privacy,pinHash:undefined});setMessage('App lock removed.')}};
  return <div className="modal-backdrop" onMouseDown={onClose}><section className="modal privacy-modal" role="dialog" aria-modal="true" aria-label="Data and privacy" onMouseDown={event=>event.stopPropagation()}><div className="modal-head"><div><small>DATA & PRIVACY</small><h2>Your information</h2></div><button className="icon" onClick={onClose} aria-label="Close"><X size={18}/></button></div>
    <div className="storage-status"><HardDrive size={23}/><span><strong>Saved on this device</strong><small>{state.privacy.lastBackupAt?`Last backup ${new Date(state.privacy.lastBackupAt).toLocaleDateString('en-US')}`:'No backup has been exported yet'}</small></span><Save size={18}/></div>
    <section className="privacy-section"><div className="privacy-section-title"><Download size={19}/><div><strong>Backup</strong><small>Protect groups, payments, attendance, tasks, and personal notes.</small></div></div><div className="privacy-actions"><button className="primary" onClick={exportData}><Download size={16}/> Export backup</button><button className="secondary" onClick={()=>inputRef.current?.click()}><Import size={16}/> Import backup</button><input ref={inputRef} className="visually-hidden" type="file" accept="application/json,.json" onChange={event=>importData(event.target.files?.[0])}/></div></section>
    <section className="privacy-section"><div className="privacy-section-title"><ShieldCheck size={19}/><div><strong>Private notifications</strong><small>Hide task, period, and ring details on the lock screen.</small></div></div><label className="period-toggle"><input type="checkbox" checked={state.notifications.privateMode} onChange={event=>onNotifications({...state.notifications,privateMode:event.target.checked})}/><span>Use neutral notification text</span></label></section>
    <section className="privacy-section"><div className="privacy-section-title"><Lock size={19}/><div><strong>App lock</strong><small>{state.privacy.pinHash?'A code is required when the app locks.':'Add a 4–8 digit code for this device.'}</small></div></div><div className="pin-row"><input aria-label="New app code" type="password" inputMode="numeric" pattern="[0-9]*" maxLength={8} value={pin} onChange={event=>setPin(event.target.value.replace(/\D/g,''))} placeholder={state.privacy.pinHash?'New code':'4–8 digits'}/><button className="secondary" onClick={savePin}>{state.privacy.pinHash?'Change':'Enable'}</button></div><p className="form-hint">The code locks the app screen. Data and exported backups remain stored locally and are not encrypted.</p>{state.privacy.pinHash&&<><label>Auto-lock<select value={state.privacy.autoLockMinutes} onChange={event=>onPrivacy({...state.privacy,autoLockMinutes:Number(event.target.value)})}><option value="0">Whenever I leave the app</option><option value="1">After 1 minute</option><option value="5">After 5 minutes</option><option value="15">After 15 minutes</option><option value="60">After 1 hour</option></select></label><div className="privacy-actions"><button className="secondary" onClick={onLock}><Lock size={16}/> Lock now</button><button className="danger" onClick={removePin}><Trash2 size={16}/> Remove code</button></div></>}</section>
    {message&&<p className="privacy-message" role="status">{message}</p>}
  </section></div>;
}

export function LockScreen({pinHash,onUnlock}:{pinHash:string;onUnlock:()=>void}){
  const [pin,setPin]=useState(''),[error,setError]=useState('');
  const unlock=async(event:React.FormEvent)=>{event.preventDefault();if(await hashPin(pin)===pinHash){setError('');onUnlock()}else{setError('That code is not correct.');setPin('')}};
  return <main className="lock-screen"><form onSubmit={unlock}><img src={`${import.meta.env.BASE_URL}icons/focus-tool-192.png`} alt=""/><small>FOCUS TOOL</small><h1>Welcome back</h1><p>Enter your app code to continue.</p><input autoFocus aria-label="App code" type="password" inputMode="numeric" pattern="[0-9]*" maxLength={8} value={pin} onChange={event=>setPin(event.target.value.replace(/\D/g,''))} placeholder="••••"/><button className="primary" disabled={!pinIsValid(pin)}><Lock size={17}/> Unlock</button>{error&&<span role="alert">{error}</span>}</form></main>;
}
