import { BellRing,CalendarHeart,CheckCheck,Clock3,ListTodo,X } from 'lucide-react';
import { useEffect } from 'react';
import type { ReminderItem } from '../lib/reminders';
import type { SystemNotificationPermission } from '../lib/systemNotifications';

const dateTime=(timestamp:number)=>new Date(timestamp).toLocaleString('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'});

export function NotificationCenter({items,dueIds,permission,onClose,onEnable,onDismissDue}:{items:ReminderItem[];dueIds:Set<string>;permission:SystemNotificationPermission;onClose:()=>void;onEnable:()=>void;onDismissDue:()=>void}){
  useEffect(()=>{const close=(event:KeyboardEvent)=>{if(event.key==='Escape')onClose()};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close)},[onClose]);
  return <div className="modal-backdrop" onMouseDown={onClose}><section className="modal notification-center" role="dialog" aria-modal="true" aria-label="Notifications" onMouseDown={event=>event.stopPropagation()}><div className="modal-head"><div><small>REMINDERS</small><h2>Notifications</h2></div><button className="icon" onClick={onClose} aria-label="Close"><X size={18}/></button></div><div className="notification-status"><BellRing size={21}/><span><strong>System notifications</strong><small>{permission==='granted'?'Enabled for this app':permission==='denied'?'Blocked — change this in device settings':permission==='unsupported'?'Unavailable here; in-app reminders still work':'Enable alerts on this device'}</small></span>{permission==='default'&&<button className="secondary compact" onClick={onEnable}>Enable</button>}</div>{dueIds.size>0&&<button className="secondary dismiss-reminders" onClick={onDismissDue}><CheckCheck size={16}/> Mark current reminders as read</button>}<div className="notification-list">{items.length?items.map(item=><article className={dueIds.has(item.id)?'due':''} key={item.id}><span className={`notification-kind ${item.kind}`}>{item.kind==='task'?<ListTodo size={18}/>:item.kind==='period'?<CalendarHeart size={18}/>:<BellRing size={18}/>}</span><div><strong>{item.title}</strong><p>{item.body}</p><small><Clock3 size={12}/>{dueIds.has(item.id)?'Reminder now':`Reminder ${dateTime(item.remindAt)}`}</small></div></article>):<div className="notifications-empty"><BellRing size={34}/><strong>No upcoming reminders</strong><span>Scheduled tasks and personal dates will appear here.</span></div>}</div></section></div>;
}
