import { useEffect,useMemo,useState } from 'react';
import { BellRing,CalendarHeart,CheckCircle2,ChevronLeft,ChevronRight,Plus,RotateCcw,Save,Settings2,Sparkles,Trash2,X } from 'lucide-react';
import { assets } from '../assets/manifest';
import { dateFromKey,localDateKey,uid } from '../lib/dates';
import { nextMarkerDate,nextPredictedStart,predictedPeriodDates,RING_REPEAT_DAYS } from '../lib/periods';
import type { PeriodMarker,PeriodTracking } from '../types';

const monthTitle=(key:string)=>{const [year,month]=key.split('-').map(Number);return new Intl.DateTimeFormat('en-US',{month:'long',year:'numeric'}).format(new Date(year,month-1,1))};
const moveMonth=(key:string,offset:number)=>{const [year,month]=key.split('-').map(Number),date=new Date(year,month-1+offset,1);return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}`};
const longDate=(key:string)=>dateFromKey(key).toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric',year:'numeric'});
const useEscapeClose=(onClose:()=>void)=>useEffect(()=>{const close=(event:KeyboardEvent)=>{if(event.key==='Escape')onClose()};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close)},[onClose]);

export function PeriodsPage({tracking,onTracking,notificationPermission,onRequestNotifications}:{tracking:PeriodTracking;onTracking:(tracking:PeriodTracking)=>void;notificationPermission:'default'|'granted'|'denied'|'unsupported';onRequestNotifications:()=>void}) {
  const [month,setMonth]=useState(localDateKey().slice(0,7));
  const [dayEditor,setDayEditor]=useState<string|null>(null);
  const [markerEditor,setMarkerEditor]=useState<Partial<PeriodMarker>|null>(null);
  const [settingsOpen,setSettingsOpen]=useState(false);
  const predicted=useMemo(()=>new Set(predictedPeriodDates(tracking,month)),[tracking,month]);
  const markerDates=useMemo(()=>new Set(tracking.markers.map(marker=>nextMarkerDate(marker)).filter((date):date is string=>Boolean(date))),[tracking.markers]);
  const next=nextPredictedStart(tracking);
  const [year,monthNumber]=month.split('-').map(Number),firstDay=new Date(year,monthNumber-1,1),offset=(firstDay.getDay()+6)%7,daysInMonth=new Date(year,monthNumber,0).getDate();
  const cells=Array.from({length:42},(_,index)=>index-offset+1);
  const saveDay=(date:string,marked:boolean,note:string)=>{const days={...tracking.days};if(marked)days[date]={note:note.trim()||undefined,updatedAt:Date.now()};else delete days[date];onTracking({...tracking,days});setDayEditor(null)};
  const saveMarker=(draft:Omit<PeriodMarker,'id'|'createdAt'|'completedAt'|'lastCompletedAt'>)=>{const editing=markerEditor?.id;const marker:PeriodMarker={id:editing!,...draft,createdAt:markerEditor?.createdAt||Date.now(),completedAt:markerEditor?.completedAt,lastCompletedAt:markerEditor?.lastCompletedAt};onTracking({...tracking,markers:editing?tracking.markers.map(item=>item.id===editing?marker:item):[...tracking.markers,{...marker,id:uid()}]});setMarkerEditor(null)};
  const removeMarker=(id:string)=>{if(window.confirm('Delete this reminder?'))onTracking({...tracking,markers:tracking.markers.filter(marker=>marker.id!==id)})};
  const completeMarker=(id:string)=>onTracking({...tracking,markers:tracking.markers.map(marker=>marker.id!==id?marker:marker.repeatDays?{...marker,date:nextDate(nextMarkerDate(marker)||marker.date,marker.repeatDays),lastCompletedAt:Date.now(),completedAt:undefined}:{...marker,completedAt:marker.completedAt?undefined:Date.now()})});

  return <section className="periods-page">
    <div className="periods-hero">
      <img src={assets.profile.moon} alt=""/>
      <div><small>PRIVATE CYCLE TRACKER</small><h1>Periods & reminders</h1><p>Mark period days, keep notes, and plan personal reminders. Everything stays on this device.</p></div>
      <button className="secondary" onClick={()=>setSettingsOpen(true)}><Settings2 size={17}/> Options</button>
    </div>
    <div className="periods-layout">
      <section className="panel period-calendar">
        <div className="period-calendar-head"><button aria-label="Previous month" onClick={()=>setMonth(value=>moveMonth(value,-1))}><ChevronLeft size={20}/></button><strong>{monthTitle(month)}</strong><button aria-label="Next month" onClick={()=>setMonth(value=>moveMonth(value,1))}><ChevronRight size={20}/></button></div>
        <div className="period-week">{['Mo','Tu','We','Th','Fr','Sa','Su'].map(day=><span key={day}>{day}</span>)}</div>
        <div className="period-grid">{cells.map((day,index)=>{if(day<1||day>daysInMonth)return <span key={index}/>;const key=`${month}-${String(day).padStart(2,'0')}`,actual=Boolean(tracking.days[key]),forecast=predicted.has(key),marker=markerDates.has(key);return <button key={key} className={`${actual?'period-day ':''}${forecast?'predicted-day ':''}${marker?'marker-day ':''}${key===localDateKey()?'today ':''}`} onClick={()=>setDayEditor(key)} aria-label={`${longDate(key)}${actual?', period recorded':''}`}>{day}{marker&&<i/>}</button>})}</div>
        <div className="period-legend"><span><i className="actual"/> Period</span>{tracking.settings.predictionEnabled&&<span><i className="forecast"/> Prediction</span>}<span><i className="reminder"/> Reminder</span></div>
      </section>
      <aside className="periods-side">
        <section className="panel cycle-card"><div><Sparkles size={21}/><small>NEXT ESTIMATE</small></div>{tracking.settings.predictionEnabled?<><strong>{next?longDate(next):'Record a period first'}</strong><p>{next?'Calculated from your saved cycle settings.':'Mark at least one period day to create an estimate.'}</p></>:<><strong>Prediction is off</strong><p>Turn it on in Options only if you want the app to calculate future dates.</p></>}<button className="secondary compact" onClick={()=>setSettingsOpen(true)}>Cycle options</button></section>
        <section className="panel personal-reminders"><div className="period-section-head"><div><small>PERSONAL REMINDERS</small><h2>Dates to remember</h2></div><BellRing size={23}/></div><div className="reminder-actions"><button className="primary compact" onClick={()=>setMarkerEditor({kind:'ring',title:'Remove vaginal ring',date:localDateKey(),time:'09:00',reminderMinutesBefore:[1440,60],repeatDays:RING_REPEAT_DAYS})}><Plus size={15}/> Ring reminder</button><button className="secondary compact" onClick={()=>setMarkerEditor({kind:'custom',date:localDateKey(),time:'09:00',reminderMinutesBefore:[1440]})}><Plus size={15}/> Custom</button></div>{tracking.markers.length?<div className="marker-list">{[...tracking.markers].sort((a,b)=>a.date.localeCompare(b.date)).map(marker=>{const shownDate=nextMarkerDate(marker)||marker.date,repeatLabel=marker.kind==='ring'&&marker.repeatDays===RING_REPEAT_DAYS?'every 4 weeks':marker.repeatDays?`every ${marker.repeatDays} days`:'';return <article className={marker.completedAt?'completed':''} key={marker.id}><button className="marker-main" onClick={()=>setMarkerEditor(marker)}><CalendarHeart size={20}/><span><strong>{marker.title}</strong><small>{longDate(shownDate)} at {marker.time}{repeatLabel?` · ${repeatLabel}`:''}</small>{marker.note&&<em>{marker.note}</em>}</span></button><button className="icon small marker-complete" aria-label={marker.completedAt?`Restore ${marker.title}`:`Complete ${marker.title}`} onClick={()=>completeMarker(marker.id)}>{marker.completedAt?<RotateCcw size={14}/>:<CheckCircle2 size={15}/>}</button><button className="icon small" aria-label={`Delete ${marker.title}`} onClick={()=>removeMarker(marker.id)}><Trash2 size={14}/></button></article>})}</div>:<div className="period-empty"><img src={assets.decorations.wand} alt=""/><span>Add a ring date or any personal reminder.</span></div>}</section>
      </aside>
    </div>
    {dayEditor&&<PeriodDayModal date={dayEditor} current={tracking.days[dayEditor]} onClose={()=>setDayEditor(null)} onSave={saveDay}/>}
    {markerEditor&&<MarkerModal marker={markerEditor} onClose={()=>setMarkerEditor(null)} onSave={saveMarker}/>}
    {settingsOpen&&<PeriodSettingsModal tracking={tracking} permission={notificationPermission} onClose={()=>setSettingsOpen(false)} onSave={onTracking} onRequestNotifications={onRequestNotifications}/>}
  </section>;
}

function PeriodDayModal({date,current,onClose,onSave}:{date:string;current?:PeriodTracking['days'][string];onClose:()=>void;onSave:(date:string,marked:boolean,note:string)=>void}){
  useEscapeClose(onClose);const [marked,setMarked]=useState(Boolean(current)),[note,setNote]=useState(current?.note||'');
  return <div className="modal-backdrop" onMouseDown={onClose}><form className="modal period-day-modal" role="dialog" aria-modal="true" aria-label="Period day" onMouseDown={event=>event.stopPropagation()} onSubmit={event=>{event.preventDefault();onSave(date,marked,note)}}><div className="modal-head"><div><small>PERIOD DAY</small><h2>{longDate(date)}</h2></div><button type="button" className="icon" onClick={onClose} aria-label="Close"><X size={18}/></button></div><label className="period-toggle"><input type="checkbox" checked={marked} onChange={event=>setMarked(event.target.checked)}/><span>Period on this day</span></label><label>Notes<textarea value={note} onChange={event=>setNote(event.target.value)} maxLength={500} placeholder="Symptoms, mood, flow, or anything you want to remember"/></label><div className="modal-actions"><button type="button" className="secondary" onClick={onClose}>Cancel</button><button className="primary"><Save size={16}/> Save day</button></div></form></div>;
}

function MarkerModal({marker,onClose,onSave}:{marker:Partial<PeriodMarker>;onClose:()=>void;onSave:(draft:Omit<PeriodMarker,'id'|'createdAt'|'completedAt'|'lastCompletedAt'>)=>void}){
  useEscapeClose(onClose);const isRing=marker.kind==='ring';const [title,setTitle]=useState(marker.title||''),[date,setDate]=useState(marker.date||localDateKey()),[time,setTime]=useState(marker.time||'09:00'),[note,setNote]=useState(marker.note||''),[repeat,setRepeat]=useState(marker.repeatDays?String(marker.repeatDays):''),[repeatRing,setRepeatRing]=useState(marker.repeatDays===RING_REPEAT_DAYS),[alerts,setAlerts]=useState<number[]>(marker.reminderMinutesBefore||[1440]);
  const toggleAlert=(minutes:number)=>setAlerts(current=>current.includes(minutes)?current.filter(item=>item!==minutes):[...current,minutes].sort((a,b)=>b-a));
  return <div className="modal-backdrop" onMouseDown={onClose}><form className="modal marker-modal" role="dialog" aria-modal="true" aria-label="Personal reminder" onMouseDown={event=>event.stopPropagation()} onSubmit={event=>{event.preventDefault();if(title.trim()&&date&&time)onSave({kind:isRing?'ring':'custom',title:title.trim(),date,time,note:note.trim()||undefined,reminderMinutesBefore:alerts.length?alerts:[0],repeatDays:isRing?(repeatRing?RING_REPEAT_DAYS:undefined):(repeat?Math.max(1,Number(repeat)||1):undefined)})}}><div className="modal-head"><h2>{marker.id?'Edit reminder':isRing?'New ring reminder':'New reminder'}</h2><button type="button" className="icon" onClick={onClose} aria-label="Close"><X size={18}/></button></div><label>Title<input autoFocus required maxLength={100} value={title} onChange={event=>setTitle(event.target.value)} placeholder="e.g. Remove vaginal ring"/></label><div className="form-grid"><label>Date<input required type="date" value={date} onChange={event=>setDate(event.target.value)}/></label><label>Time<input required type="time" value={time} onChange={event=>setTime(event.target.value)}/></label></div><fieldset className="reminder-offsets"><legend>Notify me</legend>{[[10080,'1 week before'],[1440,'1 day before'],[60,'1 hour before'],[0,'At the selected time']].map(([value,label])=><label key={value}><input type="checkbox" checked={alerts.includes(Number(value))} onChange={()=>toggleAlert(Number(value))}/><span>{label}</span></label>)}</fieldset>{isRing?<><label className="period-toggle"><input type="checkbox" checked={repeatRing} onChange={event=>setRepeatRing(event.target.checked)}/><span>Repeat every 4 weeks</span></label><p className="form-hint">This 28-day repeat option is used only for the vaginal ring reminder.</p></>:<label>Repeat every<input type="number" min="1" max="365" inputMode="numeric" value={repeat} onChange={event=>setRepeat(event.target.value)} placeholder="No repeat"/><small>days · leave empty for a one-time reminder</small></label>}<label>Notes<textarea maxLength={300} value={note} onChange={event=>setNote(event.target.value)} placeholder="Optional note shown in the notification"/></label><div className="modal-actions"><button type="button" className="secondary" onClick={onClose}>Cancel</button><button className="primary"><Save size={16}/> Save reminder</button></div></form></div>;
}

function PeriodSettingsModal({tracking,permission,onClose,onSave,onRequestNotifications}:{tracking:PeriodTracking;permission:'default'|'granted'|'denied'|'unsupported';onClose:()=>void;onSave:(tracking:PeriodTracking)=>void;onRequestNotifications:()=>void}){
  useEscapeClose(onClose);const [settings,setSettings]=useState(tracking.settings);const field=(key:keyof PeriodTracking['settings'],value:boolean|number)=>setSettings(current=>({...current,[key]:value}));
  return <div className="modal-backdrop" onMouseDown={onClose}><form className="modal period-settings-modal" role="dialog" aria-modal="true" aria-label="Period options" onMouseDown={event=>event.stopPropagation()} onSubmit={event=>{event.preventDefault();onSave({...tracking,settings:{...settings,averageCycleDays:Math.max(15,Math.min(60,settings.averageCycleDays)),averagePeriodDays:Math.max(1,Math.min(14,settings.averagePeriodDays)),periodReminderDaysBefore:Math.max(0,Math.min(14,settings.periodReminderDaysBefore))}});onClose()}}><div className="modal-head"><h2>Period options</h2><button type="button" className="icon" onClick={onClose} aria-label="Close"><X size={18}/></button></div><label className="period-toggle"><input type="checkbox" checked={settings.predictionEnabled} onChange={event=>field('predictionEnabled',event.target.checked)}/><span>Calculate future periods</span></label><p className="form-hint">Predictions are estimates based only on the cycle length you enter. They are not medical guidance.</p><div className="form-grid"><label>Average cycle<input type="number" min="15" max="60" value={settings.averageCycleDays} disabled={!settings.predictionEnabled} onChange={event=>field('averageCycleDays',Number(event.target.value))}/><small>days</small></label><label>Period length<input type="number" min="1" max="14" value={settings.averagePeriodDays} disabled={!settings.predictionEnabled} onChange={event=>field('averagePeriodDays',Number(event.target.value))}/><small>days</small></label></div><div className="form-grid"><label>Period reminder<select value={settings.periodReminderDaysBefore} disabled={!settings.predictionEnabled} onChange={event=>field('periodReminderDaysBefore',Number(event.target.value))}><option value="0">On the estimated day</option><option value="1">1 day before</option><option value="2">2 days before</option><option value="3">3 days before</option></select></label><label>Notification time<input type="time" disabled={!settings.predictionEnabled} value={settings.periodReminderTime} onChange={event=>field('periodReminderTime',event.target.value as any)}/></label></div><div className="notification-permission"><BellRing size={20}/><span><strong>System notifications</strong><small>{permission==='granted'?'Enabled':permission==='denied'?'Blocked in device settings':permission==='unsupported'?'Not available in this browser':'Permission not requested'}</small></span>{permission==='default'&&<button type="button" className="secondary compact" onClick={onRequestNotifications}>Enable</button>}</div><div className="modal-actions"><button type="button" className="secondary" onClick={onClose}>Cancel</button><button className="primary"><Save size={16}/> Save options</button></div></form></div>;
}

const nextDate=(date:string,days:number)=>{const value=dateFromKey(date);value.setDate(value.getDate()+days);return localDateKey(value)};
