import { useCallback, useEffect, useMemo, useState } from 'react';
import { CalendarDays, Check, ChevronLeft, ChevronRight, Clock3, Edit3, Flame, Focus, Moon, MoreHorizontal, Pause, Play, Plus, RotateCcw, Save, Settings2, Star, Trash2, X } from 'lucide-react';
import type { FocusToolState, Mood, Priority, Task } from './types';
import { defaults, load, resetStorage, save } from './repositories/localProgressRepository';
import { assets } from './assets/manifest';
import { dateFromKey, displayDate, localDateKey, uid } from './lib/dates';
import { completedToday, efficiency, focusMinutesToday, focusPoints, pointsToday, taskPoints, todayTasks, totalPoints } from './lib/logic';
import { encouragements } from './lib/encouragements';

type Toast = { text:string; kind?:'celebrate'|'plain' } | null;
const modeLabel = { focus:'Фокус', shortBreak:'Короткий перерыв', longBreak:'Длинный перерыв' };
const moods: {id:Mood; label:string; icon:string}[] = [{id:'great',label:'Отлично',icon:'✦'},{id:'good',label:'Хорошо',icon:'◡'},{id:'neutral',label:'Нормально',icon:'–'},{id:'tired',label:'Устал(а)',icon:'~'},{id:'low',label:'Тяжело',icon:'⌁'}];
const format = (seconds:number) => `${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`;
const minsFor = (s:FocusToolState, mode=s.activeTimer.mode) => mode === 'focus' ? s.focusSettings.focusMinutes : mode === 'shortBreak' ? s.focusSettings.shortBreakMinutes : s.focusSettings.longBreakMinutes;

function useClock() { const [now,setNow]=useState(new Date()); useEffect(()=>{const id=window.setInterval(()=>setNow(new Date()),1000);return()=>clearInterval(id)},[]); return now; }

export function App() {
  const [state,setState] = useState<FocusToolState>(() => load());
  const [now,setNow] = useState(Date.now());
  const [filter,setFilter] = useState<'today'|'upcoming'|'unscheduled'|'completed'>('today');
  const [month,setMonth] = useState(() => new Date());
  const [selectedDate,setSelectedDate] = useState(localDateKey());
  const [editor,setEditor] = useState<Partial<Task> | null>(null);
  const [resetOpen,setResetOpen] = useState(false);
  const [settingsOpen,setSettingsOpen] = useState(false);
  const [toast,setToast] = useState<Toast>(null);
  const clock = useClock();
  const today = localDateKey(clock);
  const timer = state.activeTimer;
  const remaining = timer.status === 'running' && timer.endsAt ? Math.max(0, Math.ceil((timer.endsAt-now)/1000)) : timer.remainingSeconds;

  useEffect(()=> { save(state); }, [state]);
  useEffect(()=> { const id=window.setInterval(()=>setNow(Date.now()),1000); return()=>clearInterval(id); },[]);
  useEffect(()=> { document.title = timer.status === 'running' ? `${format(remaining)} • Focus Tool` : 'Focus Tool'; },[remaining,timer.status]);
  useEffect(()=> { if (!toast) return; const id=window.setTimeout(()=>setToast(null), toast.kind==='celebrate'?5500:2500); return()=>clearTimeout(id); },[toast]);

  const update = useCallback((fn:(s:FocusToolState)=>FocusToolState) => setState(old=>fn(old)),[]);
  const completeFocus = useCallback(() => update(s => {
    const active=s.activeTimer;
    if (active.status !== 'running' || !active.endsAt || active.endsAt > Date.now()) return s;
    const planned=Math.max(1,Math.round(active.plannedSeconds/60));
    if (active.mode !== 'focus') { const next:FocusToolState={...s,activeTimer:{mode:'focus',status:'idle',plannedSeconds:s.focusSettings.focusMinutes*60,remainingSeconds:s.focusSettings.focusMinutes*60}}; setToast({text:'Перерыв завершён. Готовы к фокусу?' }); return next; }
    const sessionId=uid(), point=focusPoints(planned), completed=s.completedFocusCountSinceLongBreak+1, isLong=completed>=s.focusSettings.sessionsBeforeLongBreak, nextMode=isLong?'longBreak':'shortBreak', seconds=(isLong?s.focusSettings.longBreakMinutes:s.focusSettings.shortBreakMinutes)*60;
    setToast({text:`Фокус-сессия завершена! +${point} очков`,kind:'celebrate'});
    return {...s,focusSessions:[...s.focusSessions,{id:sessionId,taskId:active.taskId,mode:'focus',plannedMinutes:planned,startedAt:active.startedAt??Date.now(),completedAt:Date.now(),pointsAwarded:point}],pointEvents:[...s.pointEvents,{id:uid(),type:'focus_completed',points:point,createdAt:Date.now(),localDate:localDateKey(),entityId:sessionId}],completedFocusCountSinceLongBreak:isLong?0:completed,activeTimer:{mode:nextMode,status:'idle',plannedSeconds:seconds,remainingSeconds:seconds}};
  }),[]);
  useEffect(()=> { if (timer.status==='running' && remaining===0) completeFocus(); },[timer.status,remaining,completeFocus]);

  const addTask = (task:Partial<Task>) => { const title=task.title?.trim(); if (!title) return; update(s=>({...s,tasks:[...s.tasks,{id:uid(),title,status:'active',priority:(task.priority as Priority)||'medium',description:task.description||'',scheduledDate:task.scheduledDate,scheduledTime:task.scheduledTime,estimatedMinutes:task.estimatedMinutes,createdAt:Date.now(),updatedAt:Date.now(),order:s.tasks.length}]})); setEditor(null); setToast({text:'Задача добавлена'}); };
  const editTask = (task:Partial<Task>) => { if (!task.id || !task.title?.trim()) return; update(s=>({...s,tasks:s.tasks.map(x=>x.id===task.id?{...x,...task,title:task.title!.trim(),updatedAt:Date.now()}:x)})); setEditor(null); setToast({text:'Изменения сохранены'}); };
  const toggleTask = (id:string) => update(s=> { const target=s.tasks.find(t=>t.id===id); if (!target) return s; const done=target.status!=='completed'; const changed={...target,status:done?'completed' as const:'active' as const,completedAt:done?Date.now():undefined,updatedAt:Date.now()}; let next={...s,tasks:s.tasks.map(t=>t.id===id?changed:t)}; if (done && !target.rewardedCompletionId) { const reward=uid(), pts=taskPoints(target.priority); next={...next,tasks:next.tasks.map(t=>t.id===id?{...t,rewardedCompletionId:reward}:t),pointEvents:[...next.pointEvents,{id:reward,type:'task_completed',points:pts,createdAt:Date.now(),localDate:localDateKey(),entityId:id}]}; setToast({text:`Задача завершена · +${pts}`,kind:'plain'}); }
    const count=completedToday(next).length, day=localDateKey(); if(done && count>=3 && !next.milestones[day]?.threeTasksCelebrated) { const previous=next.milestones[day]?.lastEncouragement??-1; let pick=Math.floor(Math.random()*encouragements.length); if (pick===previous) pick=(pick+1)%encouragements.length; next={...next,milestones:{...next.milestones,[day]:{threeTasksCelebrated:true,lastEncouragement:pick}}}; setToast({text:encouragements[pick],kind:'celebrate'}); }
    return next;
  });
  const deleteTask=(id:string)=> { if(!window.confirm('Удалить эту задачу?')) return; update(s=>({...s,tasks:s.tasks.filter(t=>t.id!==id),activeTimer:s.activeTimer.taskId===id?{...s.activeTimer,taskId:undefined}:s.activeTimer})); setToast({text:'Задача удалена'}); };
  const chooseTask=(id?:string)=> update(s=>({...s,activeTimer:s.activeTimer.status==='idle'?{...s.activeTimer,taskId:id}:s.activeTimer}));
  const setPreset=(focus:number,breakM:number)=> update(s=>({...s,focusSettings:{...s.focusSettings,focusMinutes:focus,shortBreakMinutes:breakM},activeTimer:s.activeTimer.status==='idle'?{...s.activeTimer,mode:'focus',plannedSeconds:focus*60,remainingSeconds:focus*60}:s.activeTimer}));
  const start=()=>update(s=>{const a=s.activeTimer;if(a.status==='running')return s;const sec=a.status==='paused'?a.remainingSeconds:a.plannedSeconds;return {...s,activeTimer:{...a,status:'running',remainingSeconds:sec,startedAt:a.startedAt??Date.now(),endsAt:Date.now()+sec*1000}}});
  const pause=()=>update(s=>{const a=s.activeTimer;if(a.status!=='running')return s;const rem=Math.max(0,Math.ceil(((a.endsAt??Date.now())-Date.now())/1000));return {...s,activeTimer:{...a,status:'paused',remainingSeconds:rem,endsAt:undefined}}});
  const resetTimer=()=>update(s=>{const a=s.activeTimer,sec=minsFor(s,a.mode)*60;return {...s,activeTimer:{...a,status:'idle',startedAt:undefined,endsAt:undefined,plannedSeconds:sec,remainingSeconds:sec}}});
  const skip=()=>update(s=>{const mode=s.activeTimer.mode==='focus'?'shortBreak':'focus',sec=minsFor(s,mode)*60;return {...s,activeTimer:{mode,status:'idle',plannedSeconds:sec,remainingSeconds:sec}}});
  const currentTasks = useMemo(()=> { const sorted=[...state.tasks].sort((a,b)=>a.order-b.order); if(filter==='today')return sorted.filter(t=>t.scheduledDate===today&&t.status==='active'); if(filter==='upcoming')return sorted.filter(t=>t.scheduledDate&&t.scheduledDate>today&&t.status==='active');if(filter==='unscheduled') return sorted.filter(t=>!t.scheduledDate&&t.status==='active');return sorted.filter(t=>t.status==='completed'); },[state.tasks,filter,today]);
  const checkin=state.checkIns[today] ?? {date:today,thought:'',updatedAt:0};
  const setCheckin=(x:Partial<typeof checkin>)=>update(s=>({...s,checkIns:{...s.checkIns,[today]:{...checkin,...x,date:today,updatedAt:Date.now()}}}));
  const selectedTasks=state.tasks.filter(t=>t.scheduledDate===selectedDate).sort((a,b)=>a.order-b.order);
  const progress=timer.plannedSeconds?Math.min(100,Math.max(0,(1-remaining/timer.plannedSeconds)*100)):0;
  const todayCount=todayTasks(state,today).length, completeCount=completedToday(state,today).length, focusMin=focusMinutesToday(state,today), dailyPts=pointsToday(state,today);
  return <main className="page"><div className="organizer">
    <Header clock={clock} points={totalPoints(state)} name={state.profile.name} onProfile={()=>document.getElementById('profile')?.scrollIntoView({behavior:'smooth'})}/>
    <section className="workspace">
      <TodoPanel tasks={currentTasks} filter={filter} setFilter={setFilter} onQuick={()=>setEditor({scheduledDate:filter==='today'?today:undefined,priority:'medium'})} onToggle={toggleTask} onEdit={setEditor} onDelete={deleteTask} onFocus={chooseTask}/>
      <FocusPanel state={state} remaining={remaining} progress={progress} onStart={start} onPause={pause} onReset={resetTimer} onSkip={skip} onPreset={setPreset} onChoose={chooseTask} onSettings={()=>setSettingsOpen(!settingsOpen)} settingsOpen={settingsOpen} update={update}/>
      <aside className="right-rail"><ProfilePanel profile={state.profile.name} checkin={checkin} onName={name=>update(s=>({...s,profile:{name}}))} onCheckin={setCheckin}/><CalendarPanel month={month} setMonth={setMonth} selected={selectedDate} onSelect={setSelectedDate} tasks={state.tasks} onAdd={()=>setEditor({scheduledDate:selectedDate,priority:'medium'})} selectedTasks={selectedTasks} onEdit={setEditor}/></aside>
    </section>
    <Stats state={state} completed={completeCount} total={todayCount} focus={focusMin} points={dailyPts}/>
    <footer><span><Star size={14}/> Локальный demo-режим · всё хранится на устройстве</span><button className="danger compact" onClick={()=>setResetOpen(true)}><RotateCcw size={15}/> Сбросить</button></footer>
  </div>{editor&&<TaskEditor task={editor} onClose={()=>setEditor(null)} onSave={editor.id?editTask:addTask}/>} {resetOpen&&<ConfirmReset onClose={()=>setResetOpen(false)} onReset={()=>{resetStorage();setState(defaults());setResetOpen(false);setToast({text:'Демо-данные сброшены'});}}/>} {toast&&<div className={`toast ${toast.kind||''}`} role="status">{toast.kind==='celebrate'&&<img src={assets.rewards.crown} alt=""/>}<span>{toast.text}</span><button aria-label="Закрыть" onClick={()=>setToast(null)}><X size={16}/></button></div>}</main>;
}

function Header({clock,points,name,onProfile}:{clock:Date;points:number;name:string;onProfile:()=>void}) { return <header><div className="brand"><img src={assets.focus.emblem} alt=""/><span>FOCUS<br/><b>TOOL</b></span></div><div className="lcd header-time"><span>{displayDate(clock)}</span><strong>{clock.toLocaleTimeString('ru-RU',{hour12:false})}</strong></div><button className="score" onClick={onProfile} aria-label="Открыть профиль"><img src={assets.rewards.crystal} alt=""/><span><small>ОЧКИ</small><b>{points}</b></span><i>{name?name.slice(0,1).toUpperCase():'♡'}</i></button></header> }
function TodoPanel({tasks,filter,setFilter,onQuick,onToggle,onEdit,onDelete,onFocus}:{tasks:Task[];filter:string;setFilter:(x:any)=>void;onQuick:()=>void;onToggle:(id:string)=>void;onEdit:(t:Task)=>void;onDelete:(id:string)=>void;onFocus:(id:string)=>void}) { const labels:any={today:'Сегодня',upcoming:'Скоро',unscheduled:'Без даты',completed:'Готово'}; return <section className="panel todo"><div className="panel-title"><span>MY TASKS</span><img src={assets.decorations.wand} alt=""/></div><button className="add" onClick={onQuick}><Plus size={18}/> Добавить задачу</button><div className="filters">{Object.keys(labels).map(x=><button key={x} className={filter===x?'selected':''} onClick={()=>setFilter(x)}>{labels[x]}</button>)}</div><div className="task-list">{tasks.length?tasks.map(t=><article className={`task ${t.status}`} key={t.id}><button aria-label={t.status==='completed'?'Вернуть задачу':'Завершить задачу'} className="check" onClick={()=>onToggle(t.id)}>{t.status==='completed'&&<Check size={14}/>}</button><div className="task-copy"><strong>{t.title}</strong><span>{t.scheduledTime&&<>{t.scheduledTime} · </>}{t.estimatedMinutes&&<>{t.estimatedMinutes} мин · </>}<em className={t.priority}>{t.priority==='high'?'Высокий':t.priority==='medium'?'Средний':'Низкий'}</em></span></div><button className="icon small" onClick={()=>onFocus(t.id)} title="Фокус" aria-label="Запустить фокус"><Play size={15}/></button><details><summary aria-label="Действия"><MoreHorizontal size={17}/></summary><div><button onClick={()=>onEdit(t)}><Edit3 size={14}/> Редактировать</button><button onClick={()=>onDelete(t.id)}><Trash2 size={14}/> Удалить</button></div></details></article>):<div className="empty">Здесь пока пусто.<br/>Добавьте задачу, когда будете готовы.</div>}</div></section> }
function FocusPanel({state,remaining,progress,onStart,onPause,onReset,onSkip,onPreset,onChoose,onSettings,settingsOpen,update}:{state:FocusToolState;remaining:number;progress:number;onStart:()=>void;onPause:()=>void;onReset:()=>void;onSkip:()=>void;onPreset:(a:number,b:number)=>void;onChoose:(id?:string)=>void;onSettings:()=>void;settingsOpen:boolean;update:(x:(s:FocusToolState)=>FocusToolState)=>void}) { const a=state.activeTimer; const linked=state.tasks.find(t=>t.id===a.taskId); return <section className="panel focus-panel"><div className="panel-title"><span>FOCUS TOOL</span><button className="icon" onClick={onSettings} aria-label="Настройки таймера"><Settings2 size={17}/></button></div>{settingsOpen&&<div className="timer-settings"><label>Фокус <input type="number" min="1" value={state.focusSettings.focusMinutes} onChange={e=>update(s=>({...s,focusSettings:{...s.focusSettings,focusMinutes:+e.target.value||1}}))}/></label><label>Короткий <input type="number" min="1" value={state.focusSettings.shortBreakMinutes} onChange={e=>update(s=>({...s,focusSettings:{...s.focusSettings,shortBreakMinutes:+e.target.value||1}}))}/></label><label>Длинный <input type="number" min="1" value={state.focusSettings.longBreakMinutes} onChange={e=>update(s=>({...s,focusSettings:{...s.focusSettings,longBreakMinutes:+e.target.value||1}}))}/></label></div>}<div className={`timer-shell ${a.status==='running'?'running':''}`} style={{'--progress':`${progress*3.6}deg`} as React.CSSProperties}><img className="timer-crown" src={assets.focus.crown} alt=""/><div className="timer"><img src={assets.focus.emblem} alt=""/><small>{modeLabel[a.mode].toUpperCase()}</small><strong>{format(remaining)}</strong><span>{linked?linked.title:'Выберите задачу или начните свободно'}</span></div></div><select className="task-picker" value={a.taskId||''} disabled={a.status==='running'} onChange={e=>onChoose(e.target.value||undefined)}><option value="">Свободная фокус-сессия</option>{state.tasks.filter(t=>t.status==='active').map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select><div className="presets"><button onClick={()=>onPreset(25,5)}>25 / 5</button><button onClick={()=>onPreset(50,10)}>50 / 10</button><button onClick={()=>onPreset(90,15)}>90 / 15</button></div><div className="timer-actions">{a.status==='running'?<button className="primary" onClick={onPause}><Pause size={17}/> Пауза</button>:<button className="primary" onClick={onStart}><Play size={17}/>{a.status==='paused'?'Продолжить':'Старт'}</button>}<button className="secondary" onClick={onReset} disabled={a.status==='idle'}><RotateCcw size={16}/> Сброс</button><button className="icon" onClick={onSkip} aria-label="Сменить режим"><ChevronRight size={20}/></button></div></section> }
function ProfilePanel({profile,checkin,onName,onCheckin}:{profile:string;checkin:{mood?:Mood;thought:string};onName:(x:string)=>void;onCheckin:(x:any)=>void}) { return <section id="profile" className="panel profile"><div className="panel-title"><span>TODAY</span><img src={assets.profile.moon} alt=""/></div><label className="name"><span>Добрый день,</span><input value={profile} onChange={e=>onName(e.target.value)} placeholder="как вас зовут?"/></label><p>Как вы себя чувствуете?</p><div className="moods">{moods.map(m=><button key={m.id} className={checkin.mood===m.id?'chosen':''} onClick={()=>onCheckin({mood:m.id})} aria-label={m.label} title={m.label}><b>{m.icon}</b><small>{m.label}</small></button>)}</div><label className="thought"><span>О чём я сегодня думаю</span><textarea maxLength={800} value={checkin.thought} onChange={e=>onCheckin({thought:e.target.value})} placeholder="Спокойная заметка для себя…"/></label><small className="saved"><Save size={12}/> Сохранено локально</small></section> }
function CalendarPanel({month,setMonth,selected,onSelect,tasks,onAdd,selectedTasks,onEdit}:{month:Date;setMonth:(d:Date)=>void;selected:string;onSelect:(d:string)=>void;tasks:Task[];onAdd:()=>void;selectedTasks:Task[];onEdit:(t:Task)=>void}) { const year=month.getFullYear(), mon=month.getMonth(), start=new Date(year,mon,1).getDay(), days=new Date(year,mon+1,0).getDate(), offset=(start+6)%7; const cells=Array.from({length:42},(_,i)=>i-offset+1); const change=(n:number)=>setMonth(new Date(year,mon+n,1)); return <section className="panel calendar"><div className="calendar-head"><span>{new Intl.DateTimeFormat('ru-RU',{month:'long',year:'numeric'}).format(month)}</span><div><button onClick={()=>change(-1)} aria-label="Предыдущий месяц"><ChevronLeft size={16}/></button><button onClick={()=>{setMonth(new Date());onSelect(localDateKey())}}>Сегодня</button><button onClick={()=>change(1)} aria-label="Следующий месяц"><ChevronRight size={16}/></button></div></div><div className="week">{['Пн','Вт','Ср','Чт','Пт','Сб','Вс'].map(x=><span key={x}>{x}</span>)}</div><div className="grid">{cells.map((n,i)=>{if(n<1||n>days)return <span key={i}/>; const key=localDateKey(new Date(year,mon,n)), has=tasks.some(t=>t.scheduledDate===key), isToday=key===localDateKey();return <button key={key} onClick={()=>onSelect(key)} className={`${selected===key?'selected':''} ${isToday?'today':''}`}>{n}{has&&<i/>}</button>})}</div><div className="day-detail"><b>{dateFromKey(selected).toLocaleDateString('ru-RU',{day:'numeric',month:'long'})}</b><button className="compact secondary" onClick={onAdd}><Plus size={14}/> Задача</button>{selectedTasks.length?selectedTasks.slice(0,2).map(t=><button className="day-task" key={t.id} onClick={()=>onEdit(t)}>{t.title}</button>):<span>Ничего не запланировано</span>}</div></section> }
function Stats({state,completed,total,focus,points}:{state:FocusToolState;completed:number;total:number;focus:number;points:number}) { const score=efficiency(state); return <section className="stats"><div className="efficiency"><div className="bar"><i style={{width:`${score}%`}}/></div><div><small>ЭФФЕКТИВНОСТЬ СЕГОДНЯ</small><strong>{score}%</strong><span>{score?'Ваш ритм складывается из маленьких шагов.':'День только начинается — выберите первое дело.'}</span></div></div><div className="numbers"><div><Check size={17}/><b>{completed} / {total}</b><span>задач</span></div><div><Focus size={17}/><b>{focus}</b><span>мин фокуса</span></div><div><Flame size={17}/><b>{state.focusSessions.length}</b><span>сессий</span></div><div><Star size={17}/><b>+{points}</b><span>очков сегодня</span></div></div><img src={assets.rewards.star} alt=""/></section> }
function TaskEditor({task,onClose,onSave}:{task:Partial<Task>;onClose:()=>void;onSave:(t:Partial<Task>)=>void}) { const [form,setForm]=useState(task); const field=(key:keyof Task,value:any)=>setForm(x=>({...x,[key]:value})); return <div className="modal-backdrop" onMouseDown={onClose}><form className="modal" onMouseDown={e=>e.stopPropagation()} onSubmit={e=>{e.preventDefault();onSave(form)}}><div className="modal-head"><h2>{task.id?'Изменить задачу':'Новая задача'}</h2><button className="icon" type="button" onClick={onClose}><X size={18}/></button></div><label>Название<input autoFocus required maxLength={160} value={form.title||''} onChange={e=>field('title',e.target.value)} placeholder="Что нужно сделать?"/></label><label>Описание<textarea value={form.description||''} onChange={e=>field('description',e.target.value)} maxLength={600}/></label><div className="form-grid"><label>Дата<input type="date" value={form.scheduledDate||''} onChange={e=>field('scheduledDate',e.target.value||undefined)}/></label><label>Время<input type="time" value={form.scheduledTime||''} onChange={e=>field('scheduledTime',e.target.value||undefined)}/></label><label>Приоритет<select value={form.priority||'medium'} onChange={e=>field('priority',e.target.value)}><option value="low">Низкий</option><option value="medium">Средний</option><option value="high">Высокий</option></select></label><label>Минуты<input type="number" min="1" max="600" value={form.estimatedMinutes||''} onChange={e=>field('estimatedMinutes',e.target.value?+e.target.value:undefined)}/></label></div><div className="modal-actions"><button type="button" className="secondary" onClick={onClose}>Отмена</button><button className="primary"><Save size={16}/> Сохранить</button></div></form></div> }
function ConfirmReset({onClose,onReset}:{onClose:()=>void;onReset:()=>void}) { return <div className="modal-backdrop" onMouseDown={onClose}><div className="modal confirm" onMouseDown={e=>e.stopPropagation()}><h2>Сбросить демо-данные?</h2><p>Все задачи, очки, focus-сессии и записи Focus Tool будут удалены с этого устройства.</p><div className="modal-actions"><button className="secondary" onClick={onClose}>Отмена</button><button className="danger" onClick={onReset}><Trash2 size={16}/> Сбросить</button></div></div></div> }
